name: Deploy Allure Report to GitHub Pages

on:
  workflow_run:
    workflows: ["Playwright Tests with Allure Report"]
    types:
      - completed
  
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download Allure Report Artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: playwright.yml
        name: allure-report
        path: allure-report
      continue-on-error: true
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'allure-report'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3
